version: '2.3'
services:
  postgres:
    image: postgres:11.0
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/:/docker-entrypoint-initdb.d/
      - postgres-storage:/var/lib/postgresql/data:Z
volumes:
  postgres-storage: null